name: answers
description: Synode sur la Synodalité - Phase diocésaine
title: "[Synode]: réponses"
labels: [Synode]
body:
  - type: markdown
    attributes:
      value: |
        Merci d'insérer ici votre compte rendu.
  - type: textarea
    id: compterendu
    attributes:
      label: Compte rendu
      description: "Votre compte-rendu"
      placeholder: "Introduiser ici votre..."
    validations:
      required: true
      
